---
title: asprilo
theme: minima

header_pages:
  - checker.md
  - generator.md
  - visualizer.md
  - specification.md
  - experiments.md

plugins:
  - jekyll-relative-links

permalink: pretty

# URL of asprilo source code repo on github.com
asprilo_src_url: "https://github.com/potassco/asprilo/tree/develop"

# URL of asprilo gh-pages website on github.io
asprilo_web_url: "https://asprilo.github.io"

# Custom URLs for Uni Potsdam webspace
uniurl: "https://www.cs.uni-potsdam.de/wv"
resourceurl: "https://www.cs.uni-potsdam.de/wv/projects"
publicationurl: "https://www.cs.uni-potsdam.de/wv/publications"

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
