title: asprilo
theme: minima

header_pages:
  - checker.md
  - generator.md
  - visualizer.md
  - specification.md
  - experiments.md

plugins:
  - jekyll-relative-links

permalink: pretty

# Custom URLs for Uni Potsdam webspace
uniurl: "https://www.cs.uni-potsdam.de/wv"
resourceurl: "https://www.cs.uni-potsdam.de/wv/projects"
publicationurl: "https://www.cs.uni-potsdam.de/wv/publications"

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
